
[abstract]
== Abstract

The OGC API - Processes - Part 1: Core Standard supports the wrapping of computational tasks into executable processes that can be offered by a server through a Web API and be invoked by a client application. The standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The standard leverages concepts from the OGC Web Processing Service (WPS) 2.0 Interface Standard but does not require implementation of a WPS.

By way of background and context, in many cases geospatial or location data, including data from sensors, must be processed before the information can be effectively used. The WPS Standard provides a standard interface that simplifies the task of making simple or complex computational geospatial processing services accessible via web services. Such services include well-known processes found in Geographic Information Systems (GIS) as well as specialized processes for spatiotemporal modeling and simulation. While the WPS standard was designed with spatial processing in mind, the standard could also be used to readily insert non-spatial processing tasks into a web services environment.

The OGC API - Processes Standard is a newer and more modern way of programming and interacting with resources over the web while allowing better integration into existing software packages. The OGC API - Processes Standard addresses all of the use cases that were addressed by the WPS Standard, while also leveraging the OpenAPI specification and a resource-oriented approach.

The resources that are provided by a server implementing the OGC API - Processes Standard are listed in <<table_core_resources>> below and include information about the server, the list of available processes (Process list and Process description), jobs (running processes) and
results of process executions.


[[table_core_resources]]
.Requirements class 'Core' - Overview of resources, applicable HTTP methods and links to the document sections
[cols="27,25,10,10,28",options="header"]
|===
| Resource | Path | HTTP method | Parameter | Document reference

|Landing page |`/` |GET| N/A | <<sc_landing_page>>
|Conformance classes |`/conformance` |GET| N/A | <<sc_conformance_classes>>
|Process list |`/processes` |GET | N/A | <<sc_process_list>>
|Process description |`/processes/{processID}` |GET | processID (in path) | <<sc_process_description>>
|Process execution |`/processes/{processID}/execution` |POST| processID (in path), Execute request (contained in body) |<<sc_create_job>>
|Job status info |`/jobs/{jobID}` |GET | jobID (in path) |<<sc_retrieve_status_info>>
|Job results |`/jobs/{jobID}/results` |GET |  jobID (in path) |<<sc_retrieve_job_results>>
|===

In general, the HTTP GET operation is used to provide access to the resources described above.
However, in order to execute a process, the HTTP POST method is used to send an execution request to the server.

Additionally, the /jobs endpoint can be used to grant access to a list of jobs.


.Requirements class 'Job list' - Overview of resources, applicable HTTP methods and links to the document sections
[cols="27,25,10,10,28",options="header"]
|===
|Resource |Path |HTTP method | Parameter| Document reference
|Job list |`/jobs` |GET | N/A |<<sc_job_list>>
|===

In addition to the operations accessible through HTTP GET and POST methods, the DELETE method can be used to cancel a job execution and/or remove traces of the job execution.


.Requirements class 'Dismiss' - Overview of resources, applicable HTTP methods and links to the document sections
[cols="27,25,10,10,28",options="header"]
|===
|Resource |Path |HTTP method | Parameter| Document reference
|Job status info |`/jobs/{jobID}` |DELETE| jobID (in path) | <<Dismiss>>
|===


.Preface

The OGC API - Processes - Part 1: Core Standard supports the wrapping of computational tasks into executable processes that can be offered by a server through a Web API and be invoked by a client application. Examples of computational processes that can be supported by implementations of this specification include raster algebra, geometry buffering, constructive area geometry, routing, imagery analysis and several others.


== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
|===
| Name | Affiliation

|Benjamin Pross _(editor)_ | 52°North GmbH
|Stan Tillman|Hexagon
|Panagiotis (Peter) A. Vretanos _(editor)_ |CubeWerx Inc.
|Jérôme Jacovella-St-Louis|Ecere Corporation
|Pedro Gonçalves|Terradue Srl
|Gérald Fenoy| Gérald Fenoy (Individual Member)
|Cristiano Lopes|European Space Agency (ESA)
|Christophe Noel | Spacebel

|===
